[build]
  publish = ".next"
  command = "npm run build"

[[headers]]
  for = "/source-images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "public/images/*"
  [headers.values]
    Cache-Control = "public, max-age=4300, must-revalidate"

